In [6]:
import numpy as np
v = np.linspace(0,12,5)
v

array([ 0.,  3.,  6.,  9., 12.])

In [7]:
v[0]

np.float64(0.0)

In [8]:
v[1]

np.float64(3.0)

In [9]:
v[-1]

np.float64(12.0)

In [10]:
vv = np.random.randn(5, 4)
vv

array([[ 1.17033791,  0.15960431,  0.21822688,  1.22222122],
       [-0.0245057 , -0.39704938, -0.64103562, -0.58246975],
       [-1.59206976,  0.08634082,  0.85013878, -1.82575132],
       [-0.14616271,  0.97407437,  1.30233228, -0.2139532 ],
       [ 0.44096846, -0.10120841, -0.39194206, -0.79370517]])

In [12]:
vv[0,0]

np.float64(1.1703379145476176)

In [13]:
vv[1,3]

np.float64(-0.5824697453950217)

In [14]:
vv[3,1]

np.float64(0.9740743699577324)

In [15]:
ll = [[1,2,3], [4,5,6], [7,8,9]]
ll

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
ll[1]

[4, 5, 6]

In [17]:
ll[1][2]

6

In [18]:
v[2:4]

array([6., 9.])

In [19]:
vv[2:5, 1]

array([ 0.08634082,  0.97407437, -0.10120841])

In [21]:
vv[2:5, 1:2]

array([[ 0.08634082],
       [ 0.97407437],
       [-0.10120841]])

In [22]:
vv[0:-2, :]

array([[ 1.17033791,  0.15960431,  0.21822688,  1.22222122],
       [-0.0245057 , -0.39704938, -0.64103562, -0.58246975],
       [-1.59206976,  0.08634082,  0.85013878, -1.82575132]])

In [23]:
# every other element 
vv[:, ::2]

array([[ 1.17033791,  0.21822688],
       [-0.0245057 , -0.64103562],
       [-1.59206976,  0.85013878],
       [-0.14616271,  1.30233228],
       [ 0.44096846, -0.39194206]])

In [24]:
v2 = v[2:4]
v2

array([6., 9.])

In [25]:
v2[0] = 0
v2

array([0., 9.])

In [26]:
v

array([ 0.,  3.,  0.,  9., 12.])

In [27]:
v3 = v[2:4].copy().transpose()
v3


array([0., 9.])

In [28]:
v3 = v[2:4].copy()
v3


array([0., 9.])

In [29]:
v3

array([0., 9.])

In [30]:
v3[0] = 2
v3

array([2., 9.])

In [31]:
v

array([ 0.,  3.,  0.,  9., 12.])

In [32]:
v[[1,2,3,]]

array([3., 0., 9.])

In [36]:
bool_index = v > 0
bool_index

array([False,  True, False,  True,  True])

In [37]:
v[bool_index]

array([ 3.,  9., 12.])

In [38]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [39]:
vv

array([[ 2.34067583,  0.15960431,  0.21822688,  2.44444244],
       [-0.0245057 , -0.39704938, -0.64103562, -0.58246975],
       [-1.59206976,  0.08634082,  1.70027755, -1.82575132],
       [-0.14616271,  1.94814874,  2.60466455, -0.2139532 ],
       [ 0.44096846, -0.10120841, -0.39194206, -0.79370517]])