In [6]:
import numpy as np

In [8]:
v = np.linspace(0,10,5)
v

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
v[0]

np.float64(0.0)

In [12]:
v[1]

np.float64(2.5)

In [13]:
v[-1]

np.float64(10.0)

In [14]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [15]:
vv = np.random.random((5,4))

In [16]:
vv

array([[0.55284618, 0.78595129, 0.05357769, 0.67866713],
       [0.37397335, 0.96309807, 0.12908455, 0.50197633],
       [0.94101534, 0.66732567, 0.68439828, 0.39422646],
       [0.86659719, 0.68134372, 0.52723646, 0.92093861],
       [0.48141535, 0.81196269, 0.45354062, 0.50369212]])

In [17]:
vv[0,0]

np.float64(0.5528461755956868)

In [18]:
vv[4,3]

np.float64(0.5036921249574401)

In [19]:
ll = [[1,2,3],[4,5,6],[7,8,9]]

In [20]:
ll[1,2]

TypeError: list indices must be integers or slices, not tuple

In [21]:
ll[1][2]

6

In [22]:
v[2:4]

array([5. , 7.5])

In [23]:
vv[2:5,1]

array([0.66732567, 0.68134372, 0.81196269])

In [24]:
vv[2:5,1:2]

array([[0.66732567],
       [0.68134372],
       [0.81196269]])

In [25]:
vv[2:-1,:]

array([[0.94101534, 0.66732567, 0.68439828, 0.39422646],
       [0.86659719, 0.68134372, 0.52723646, 0.92093861]])

In [29]:
vv[:,::2]

array([[0.55284618, 0.05357769],
       [0.37397335, 0.12908455],
       [0.94101534, 0.68439828],
       [0.86659719, 0.52723646],
       [0.48141535, 0.45354062]])

In [31]:
v2 = v[2:4]
v2

array([5. , 7.5])

In [32]:
v2[0] = 0

In [33]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [34]:
v3 = v[2:4].copy()

In [35]:
v3[0] = 1

In [36]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [37]:
v[[1,2,3]]

array([2.5, 0. , 7.5])

In [39]:
bool_index = v > 0
bool_index

array([False,  True, False,  True,  True])

In [40]:
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [41]:
vv[vv > 0.5] = vv[vv > 0.5] * 2

In [42]:
vv

array([[1.10569235, 1.57190257, 0.05357769, 1.35733427],
       [0.37397335, 1.92619614, 0.12908455, 1.00395266],
       [1.88203068, 1.33465133, 1.36879656, 0.39422646],
       [1.73319439, 1.36268744, 1.05447293, 1.84187722],
       [0.48141535, 1.62392537, 0.45354062, 1.00738425]])