In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a.dtype

dtype('int64')

In [6]:
a = np.array([1,2,3,4,5],dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [7]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [8]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)

In [9]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [12]:
np.zeros((3,3),'d')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.empty((4,4),'d')

array([[6.23042070e-307, 4.67296909e-307, 1.69121096e-306,
        1.37961709e-306],
       [1.42418987e-306, 1.37961641e-306, 1.60220528e-306,
        1.24611266e-306],
       [9.34598925e-307, 1.24612081e-306, 1.11260755e-306,
        1.60220393e-306],
       [1.51320640e-306, 9.34609790e-307, 1.24610723e-306,
        8.35461349e-309]])

In [15]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.random.standard_normal((2,4))

array([[ 0.51958661,  0.40002412, -0.79664408, -0.52085114],
       [-1.33001856,  0.62945525,  0.26323224, -0.36020453]])

In [18]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[-0.1783684 ,  1.38027139,  0.61179393],
       [ 0.69389533,  1.6934884 ,  0.84255661],
       [ 2.17297849, -0.1754504 ,  1.99545508],
       [ 0.22833347,  0.16093486,  0.79346655]])

In [19]:
np.hstack([a,b])

array([[-0.1783684 ,  1.38027139,  0.61179393,  2.17297849, -0.1754504 ,
         1.99545508],
       [ 0.69389533,  1.6934884 ,  0.84255661,  0.22833347,  0.16093486,
         0.79346655]])

In [20]:
a.transpose()

array([[-0.1783684 ,  0.69389533],
       [ 1.38027139,  1.6934884 ],
       [ 0.61179393,  0.84255661]])

In [21]:
np.save('example.npy',a)

In [22]:
a1 = np.load('example.npy')

In [23]:
a1

array([[-0.1783684 ,  1.38027139,  0.61179393],
       [ 0.69389533,  1.6934884 ,  0.84255661]])