In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [6]:
a.dtype

dtype('int64')

In [12]:
a = np.array([1,2,4,5,7], dtype=np.float64)
a

array([1., 2., 4., 5., 7.])

In [13]:
print(a)
a.ndim, a.shape, a.size

[1. 2. 4. 5. 7.]


(1, (5,), 5)

In [15]:
b = np.array(([1,2,3,4], [5,6,7,8]), dtype=np.int32)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

In [20]:
b.dtype

dtype('int32')

In [21]:
np.zeros((3,4),'d')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.empty((2,4), 'd')

array([[9.76118064e-313, 2.43951903e-312, 2.37663529e-312,
        2.41907520e-312],
       [2.22809558e-312, 2.22809558e-312, 2.33419537e-312,
        1.94693963e-308]])

In [24]:
np.linspace(0,12,5)

array([ 0.,  3.,  6.,  9., 12.])

In [25]:
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

In [26]:
np.random.standard_normal((2, 5))

array([[-1.82285639,  0.88754429,  1.1758344 ,  1.06724395, -2.28032483],
       [ 2.39085962,  0.58150974, -0.86866645, -2.73409092, -0.06319211]])

In [29]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a, b])

array([[ 1.96829974,  0.94427889,  0.45248408],
       [-1.60361697, -0.95908023,  1.1884518 ],
       [ 0.46487307,  0.55143718,  0.15677579],
       [-0.09347502, -0.04170524, -1.20409514]])

In [30]:
np.hstack([a, b])

array([[ 1.96829974,  0.94427889,  0.45248408,  0.46487307,  0.55143718,
         0.15677579],
       [-1.60361697, -0.95908023,  1.1884518 , -0.09347502, -0.04170524,
        -1.20409514]])

In [31]:
a.transpose()

array([[ 1.96829974, -1.60361697],
       [ 0.94427889, -0.95908023],
       [ 0.45248408,  1.1884518 ]])

In [ ]:
np.save('example.npy',a)

In [ ]:
a1 = np.load('example.npy')